---
- name: Rulebook to print debug message based on webhook event
  inventories: 
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 127.0.0.1
          port: 6000

  rules:
      - name: Launch playbook on start command
        condition: event.payload.command == 'start'
        action:
           run_job_template:
               name: playbook.yml
               extra_vars:
                   eventSource: "{{ eventSource }}"
